### ISSUE TITLE
[BUG?]看Pica出现错误

### ISSUE THREAD

**Issue by BlackTitle** [Soung2279/pica#3]
`[2022-09-11 20:04:19,858 nonebot] INFO: Self: 471425760, Message 523715968 from 2775116592@[群:750549030]: '看pica (C95) &#91;P:P (おりょう)&#93;  麻衣先輩といちゃつきたい(青春ブタ野郎はバニーガール先輩の夢を見ない) &#91;中国翻訳&#93;'
[2022-09-11 20:04:19,858 PICA] INFO: Message 523715968 triggered get_pica.
[2022-09-11 20:04:20,043 PICA] ERROR: <class 'KeyError'> occured when get_pica handling message 523715968.
[2022-09-11 20:04:20,043 PICA] ERROR: 'data'
Traceback (most recent call last):
  File "C:\BOT\HoshinoBot-master\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\BOT\HoshinoBot-master\hoshino\modules\pikapika\main.py", line 510, in get_pica
    name = src_data["data"]["comic"]["title"].strip()
KeyError: 'data'`

以上为当时的错误代码,已按照教程填写需填写内容。
且尝试了更换其他本子名，也提示此信息
随机本子可以正常下载,虽然提示 '消息已响应, 但上传失败.请查看日志窗口' 但已经压缩完了

**Comment by dfmjndm** [comment]
和我那个issue一样
