### ISSUE TITLE
图片存放文件夹问题

### ISSUE THREAD

**Issue by becteria** [Soung2279/pica#5]
这是报错2022-10-25 11:43:09 INFO Self: 1625183495, Message -838302648 from 1360532433@[群:851166132]: '随机本子'
[2022-10-25 11:43:09,575 PICA] INFO: Message -838302648 triggered get_pica_random.
2022-10-25 11:43:09 INFO Message -838302648 triggered get_pica_random.
[2022-10-25 11:43:12,537 PICA] ERROR: <class 'IndexError'> occured when get_pica_random handling message -838302648.
2022-10-25 11:43:12 ERROR <class 'IndexError'> occured when get_pica_random handling message -838302648.
[2022-10-25 11:43:12,537 PICA] ERROR: list index out of range
Traceback (most recent call last):
  File "D:\bot\hoshino-paimon\HoshinoBot\hoshino\msghandler.py", line 21, in handle_message
    await service_func.func(bot, event)
  File "D:\bot\hoshino-paimon\HoshinoBot\hoshino\service.py", line 224, in wrapper
    return await func(bot, event)
  File "D:\bot\hoshino-paimon\HoshinoBot\hoshino\modules\pica\main.py", line 582, in get_pica_random
    out = res["data"]["comics"]["docs"][0]
IndexError: list index out of range
2022-10-25 11:43:12 ERROR list index out of range
Traceback (most recent call last):
  File "D:\bot\hoshino-paimon\HoshinoBot\hoshino\msghandler.py", line 21, in handle_message
    await service_func.func(bot, event)
  File "D:\bot\hoshino-paimon\HoshinoBot\hoshino\service.py", line 224, in wrapper
    return await func(bot, event)
  File "D:\bot\hoshino-paimon\HoshinoBot\hoshino\modules\pica\main.py", line 582, in get_pica_random
    out = res["data"]["comics"]["docs"][0]
IndexError: list index out of range

**Comment by becteria** [comment]
这是我文件夹位置，是搞错了吗？？#pica存放的文件夹
pica_folder = "D:\bot\hoshino-paimon\HoshinoBot\res\img\pica"

**Comment by becteria** [comment]
![测试1](https://user-images.githubusercontent.com/51076246/197678670-8e04ea21-914d-4feb-839c-46de03270263.png)

![测试1](https://user-images.githubusercontent.com/51076246/197678692-552eec36-a067-488c-97d9-dbe3c708ccb9.png)

**Comment by becteria** [comment]
1.
